import { StyleSheet, Dimensions } from 'react-native';

const { width } =  Dimensions.get('window');

export const gStyle = StyleSheet.create({
  container: {
    flex: 1,
    overflow: 'hidden',
  },
  map: {
    width: '100%',
    height: '100%',
  },
  card: {
    width: '100%',
    height: 310,
    backgroundColor: '#EE5407',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    bottom: 0,
    backgroundColor: 'rgba(30, 30, 30, 0.35)',
    borderTopLeftRadius: 50,
    borderTopRightRadius: 50,
    overflow: 'hidden',  
  }, 
  list: {
    width: 363,
    height: 240,
    position: 'absolute',
    top: 15,
    backgroundColor: 'rgba(30,30,30, 0)',
    borderRadius: 50,
    overflow: 'hidden',
  },
  item: {
    textAlign: 'center',
    fontSize: '17',
    color: 'white',
    height: '100%',
    borderColor: 'white',
    borderWidth: 0,
    width: 363,
    backgroundColor: '#413F3F',
    overflow: 'scroll',
    borderRadius: 50,
  },
  indicatorplace: {
    width:  250,
    height: 25,
    position: 'absolute',
    bottom: 15,
    backgroundColor: '#1e1e1e',
    borderRadius: 50,
    overflow: 'hidden',
  },
  indicator1: {
    width:  25,
    height: 25,
    position: 'absolute',
    bottom: 0,
    backgroundColor: 'rgba(113,224,110, 0.25)',
    borderRadius: 50,
    overflow: 'hidden',
  },
  indicator2: {
    width:  50,
    height: 25,
    position: 'absolute',
    bottom: 0,
    backgroundColor: 'rgba(181,231,91, 0.3)',
    borderRadius: 50,
    overflow: 'hidden',
  },
  indicator3: {
    width:  75,
    height: 25,
    position: 'absolute',
    bottom: 0,
    backgroundColor: 'rgba(210,234,82, 0.2)',
    borderRadius: 50,
    overflow: 'hidden',
  },
  indicator4: {
    width:  100,
    height: 25,
    position: 'absolute',
    bottom: 0,
    backgroundColor: 'rgba(233,236,75, 0.3)',
    borderRadius: 50,
    overflow: 'hidden',
  },
  indicator5: {
    width:  125,
    height: 25,
    position: 'absolute',
    bottom: 0,
    backgroundColor: 'rgba(233,228,78, 0.3)',
    borderRadius: 50,
    overflow: 'hidden',
  },
  indicator6: {
    width:  150,
    height: 25,
    position: 'absolute',
    bottom: 0,
    backgroundColor: 'rgba(232,218,81, 0.3)',
    borderRadius: 50,
    overflow: 'hidden',
  },
  indicator7: {
    width:  175,
    height: 25,
    position: 'absolute',
    bottom: 0,
    backgroundColor: 'rgba(230,191,89, 0.3)',
    borderRadius: 50,
    overflow: 'hidden',
  },
  indicator8: {
    width:  200,
    height: 25,
    position: 'absolute',
    bottom: 0,
    backgroundColor: 'rgba(228,160,97, 0.3)',
    borderRadius: 50,
    overflow: 'hidden',
  },
  indicator9: {
    width:  225,
    height: 25,
    position: 'absolute',
    bottom: 0,
    backgroundColor: 'rgba(226,134,105, 0.3)',
    borderRadius: 50,
    overflow: 'hidden',
  },
  indicator10: {
    width:  250,
    height: 25,
    position: 'absolute',
    bottom: 0,
    backgroundColor: '#E17070',
    borderRadius: 50,
    overflow: 'hidden',
  },
  text: {
    marginTop: 5,
    marginBottom: 5,
    textAlign: 'center',
    fontSize: '20',
    color: 'white',
    fontWeight: 'bold',
  },
  panelitem: {
    textAlign: 'center',
    color: 'none',
    height: 65,
    borderColor: 'white',
    borderWidth: 0,
    width: 65,
    backgroundColor: '#EEEFF3',
    overflow: 'scroll',
    borderRadius: 18,
    marginRight: 20,
    top: 10,
    left: 20,
  },
  panelcard: {
    width: '100%',
    height: 170.5,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    bottom: 0,
    backgroundColor: '#FBFCFE',
    overflow: 'hidden',  
    
  }, 
  panellist: {
    left: 0,
    width: width,
    height: 85,
    position: 'absolute',
    bottom: 73,
    backgroundColor: 'rgba(30,30,30, 0)',
    overflow: 'hidden',
    shadowOffset: {
      width: 1,
      height: 1,
    },
    shadowRadius: 5,
    shadowOpacity: 0.25,
    shadowColor: '#171717',
  },
})